


const Stats = () => {

  return (
    <div className=" relative bg-[url('../images/galllery-image4.jpg')] bg-center bg-cover bg-fixed before:absolute before:w-full before:h-full before:inset-0 before:bg-black/65 z-10 before:-z-10   p-8 min-h-[500px] flex flex-col items-center justify-center font-[sans-serif]">
      <h2 className=" text-5xl max-md:text-4xl font-semibold mb-16 text-center text-[#fff]">OUR  ACHIEVEMENTS</h2>
      <div className="grid lg:grid-cols-4 sm:grid-cols-2 gap-6 max-lg:gap-12">
        <div className="text-center">
          <h3 className="text-white text-4xl font-extrabold">5.4<span className="text-[#f9a334]">M+</span></h3>
          <p className="text-lg font-bold mt-1 text-[#f9a334]">Total Users</p>
          <p className="text-sm text-white mt-2">The total number of registered users on the platform.</p>
        </div>
        <div className="text-center">
          <h3 className="text-white text-4xl font-extrabold">$80<span className="text-[#f9a334]">K</span></h3>
          <p className="text-lg font-bold mt-1 text-[#f9a334]">Revenue</p>
          <p className="text-sm text-white mt-2">The total revenue generated by the application.</p>
        </div>
        <div className="text-center">
          <h3 className="text-white text-4xl font-extrabold">100<span className="text-[#f9a334]">K</span></h3>
          <p className="text-lg font-bold mt-1 text-[#f9a334]">Engagement</p>
          <p className="text-sm text-white mt-2">The level of user engagement with the application&apos;s content and features.</p>
        </div>
        <div className="text-center">
          <h3 className="text-white text-4xl font-extrabold">99.9<span className="text-[#f9a334]">%</span></h3>
          <p className="text-lg font-bold mt-1 text-[#f9a334]">Server Uptime</p>
          <p className="text-sm text-white mt-2">The percentage of time the server has been operational and available.</p>
        </div>
      </div>
    </div>
   
  )
}

export default Stats